// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_height_from_u64`, `catch`, `discover_software_account_at_index`, `discover_used_software_accounts`, `discovery_start_height`, `import_discovered_software_wallet_accounts`, `import_software_account_for_existing_wallet`, `is_ironwood_active_at_height`, `network_name`, `nu6_3_activation_height`, `parse_network_and_migrate`, `preview_transparent_balance_for_addresses`

/// Get the latest block height from lightwalletd.
Future<BigInt> getLatestBlockHeight({required String lightwalletdUrl}) =>
    RustLib.instance.api.crateApiWalletGetLatestBlockHeight(
      lightwalletdUrl: lightwalletdUrl,
    );

/// Get the lightwalletd chain name ("main" or "test") for endpoint validation.
Future<String> getLightwalletdChainName({required String lightwalletdUrl}) =>
    RustLib.instance.api.crateApiWalletGetLightwalletdChainName(
      lightwalletdUrl: lightwalletdUrl,
    );

/// Get the connected chain upgrade state used to decide whether Ironwood is active.
Future<ChainUpgradeStatus> getChainUpgradeStatus({
  required String lightwalletdUrl,
  required String network,
}) => RustLib.instance.api.crateApiWalletGetChainUpgradeStatus(
  lightwalletdUrl: lightwalletdUrl,
  network: network,
);

/// Compute chain upgrade activation state from a known chain tip height.
Future<ChainUpgradeActivationStatus> getChainUpgradeStatusAtHeight({
  required String network,
  required BigInt tipHeight,
}) => RustLib.instance.api.crateApiWalletGetChainUpgradeStatusAtHeight(
  network: network,
  tipHeight: tipHeight,
);

/// Create a new Zcash wallet with a fresh mnemonic.
/// birthday_height should be the current chain tip (from get_latest_block_height).
Future<WalletCreationResult> createWallet({
  required String network,
  required String dbPath,
  BigInt? birthdayHeight,
  String? accountName,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  network: network,
  dbPath: dbPath,
  birthdayHeight: birthdayHeight,
  accountName: accountName,
);

/// Import an existing wallet from a mnemonic phrase.
Future<WalletImportResult> importWallet({
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  String? accountName,
}) => RustLib.instance.api.crateApiWalletImportWallet(
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  birthdayHeight: birthdayHeight,
  network: network,
  dbPath: dbPath,
  accountName: accountName,
);

/// Add an additional account to an existing wallet database.
Future<AccountCreationResult> addAccount({
  required String dbPath,
  required String network,
  required String name,
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
}) => RustLib.instance.api.crateApiWalletAddAccount(
  dbPath: dbPath,
  network: network,
  name: name,
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  birthdayHeight: birthdayHeight,
);

/// Discover higher ZIP32 software accounts with transparent history that are
/// not already present in the wallet DB for this mnemonic.
Future<SoftwareWalletImportDiscoveryResult>
discoverSoftwareWalletImportAccounts({
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  required String lightwalletdUrl,
  required bool isFirstWalletAccount,
}) => RustLib.instance.api.crateApiWalletDiscoverSoftwareWalletImportAccounts(
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  birthdayHeight: birthdayHeight,
  network: network,
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  isFirstWalletAccount: isFirstWalletAccount,
);

/// Preview the spendable transparent UTXO balance for a software ZIP32 account.
///
/// This does not import the account or touch the wallet DB. It checks a bounded
/// standard BIP44 transparent address range so the onboarding modal can update
/// balance rows after discovery has already returned.
Future<BigInt> previewSoftwareAccountTransparentBalance({
  required String mnemonic,
  required String bip39Passphrase,
  required String network,
  required String lightwalletdUrl,
  required int zip32AccountIndex,
}) =>
    RustLib.instance.api.crateApiWalletPreviewSoftwareAccountTransparentBalance(
      mnemonic: mnemonic,
      bip39Passphrase: bip39Passphrase,
      network: network,
      lightwalletdUrl: lightwalletdUrl,
      zip32AccountIndex: zip32AccountIndex,
    );

/// Import a software mnemonic. `account'=0` must be imported successfully;
/// higher account indices are imported only when selected by the caller.
Future<SoftwareWalletImportWithDiscoveryResult>
importSoftwareWalletWithAccountDiscovery({
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  String? firstAccountName,
  required bool isFirstWalletAccount,
  required int nextAccountNumber,
  required List<int> additionalAccountIndices,
}) =>
    RustLib.instance.api.crateApiWalletImportSoftwareWalletWithAccountDiscovery(
      mnemonic: mnemonic,
      bip39Passphrase: bip39Passphrase,
      birthdayHeight: birthdayHeight,
      network: network,
      dbPath: dbPath,
      firstAccountName: firstAccountName,
      isFirstWalletAccount: isFirstWalletAccount,
      nextAccountNumber: nextAccountNumber,
      additionalAccountIndices: additionalAccountIndices,
    );

/// Import exactly one software ZIP32 account for encrypted wallet-link imports.
///
/// Account 0 remains a Derived seed-anchor when it is the first wallet account.
/// If the first selected account is a higher ZIP32 index, the wallet is
/// initialized without a seed and that selected account is imported by UFVK so
/// the mobile import matches the user's selection instead of silently adding
/// account 0.
Future<SoftwareWalletImportAccount> importSoftwareAccountAtIndex({
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  required String name,
  required int zip32AccountIndex,
  required bool isFirstWalletAccount,
}) => RustLib.instance.api.crateApiWalletImportSoftwareAccountAtIndex(
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  birthdayHeight: birthdayHeight,
  network: network,
  dbPath: dbPath,
  name: name,
  zip32AccountIndex: zip32AccountIndex,
  isFirstWalletAccount: isFirstWalletAccount,
);

/// Derive the next account from a recovery phrase that already has at least
/// one account in this wallet (ZIP 32 HD derivation — issue #266).
///
/// Atomically picks the lowest unused ZIP 32 account index for the seed's
/// fingerprint. Deleted indices are re-derived before new indices are
/// allocated, keeping the index space compact for import-time discovery.
/// Routing matches `import_software_account_at_index`: `Derived` via
/// `import_account_hd` when the seed's anchor exists, otherwise `Imported`
/// with derivation metadata.
///
/// `operation_token` is issued by `begin_software_account_derivation_lease`.
/// Rust keeps the OS-level lease until Dart durably commits or aborts the
/// matching recovery journal, so another process cannot allocate around it.
Future<SoftwareWalletImportAccount> deriveNextSoftwareAccount({
  required String mnemonic,
  required String bip39Passphrase,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  required String name,
  required String operationToken,
}) => RustLib.instance.api.crateApiWalletDeriveNextSoftwareAccount(
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  birthdayHeight: birthdayHeight,
  network: network,
  dbPath: dbPath,
  name: name,
  operationToken: operationToken,
);

/// Acquire the native lease for a software-account derivation before Dart
/// writes its recovery journal. The lease remains held across FFI calls.
Future<SoftwareAccountDerivationLease> beginSoftwareAccountDerivationLease({
  required String dbPath,
  required String network,
  required String sourceAccountUuid,
  required String recoveryName,
  required String recoveryProfilePictureId,
  String? recoveryAccountGroupName,
}) => RustLib.instance.api.crateApiWalletBeginSoftwareAccountDerivationLease(
  dbPath: dbPath,
  network: network,
  sourceAccountUuid: sourceAccountUuid,
  recoveryName: recoveryName,
  recoveryProfilePictureId: recoveryProfilePictureId,
  recoveryAccountGroupName: recoveryAccountGroupName,
);

/// Reclaim a crash-left pending record only with the stable opaque operation
/// token from its matching versioned Dart fence. The held OS lock, not this
/// durable identifier, establishes process ownership.
Future<SoftwareAccountDerivationLease> resumeSoftwareAccountDerivationLease({
  required String dbPath,
  required String previousOperationToken,
}) => RustLib.instance.api.crateApiWalletResumeSoftwareAccountDerivationLease(
  dbPath: dbPath,
  previousOperationToken: previousOperationToken,
);

/// Claim a native pending record when the Dart fence was never written (or was
/// lost). The returned immutable intent lets Dart rebuild the exact fence
/// before it reconciles any account delta. If Dart already cleared its fence
/// and crashed before finalization, this also prunes the resolved record and
/// returns `None` while still holding the shared mutation gate.
Future<SoftwareAccountDerivationLease?>
claimPendingSoftwareAccountDerivationLease({required String dbPath}) => RustLib
    .instance
    .api
    .crateApiWalletClaimPendingSoftwareAccountDerivationLease(dbPath: dbPath);

/// Mark the authenticated persistent record resolved only when Rust proves the
/// current DB delta is either empty (abort) or exactly `account_uuid` (commit).
Future<void> resolveSoftwareAccountDerivationLease({
  required String operationToken,
  String? accountUuid,
}) => RustLib.instance.api.crateApiWalletResolveSoftwareAccountDerivationLease(
  operationToken: operationToken,
  accountUuid: accountUuid,
);

/// Delete the resolved native recovery record after Dart has durably removed
/// its matching recovery fence.
Future<void> finalizeSoftwareAccountDerivationLease({
  required String operationToken,
}) => RustLib.instance.api.crateApiWalletFinalizeSoftwareAccountDerivationLease(
  operationToken: operationToken,
);

/// Release a derivation lease after the matching durable journal has been
/// committed or safely retained for recovery.
Future<void> finishSoftwareAccountDerivationLease({
  required String operationToken,
}) => RustLib.instance.api.crateApiWalletFinishSoftwareAccountDerivationLease(
  operationToken: operationToken,
);

/// Acquire the shared account-mutation gate for one account deletion. Native
/// pending derivation recovery must be resolved before this succeeds.
Future<String> beginAccountDeletionLease({required String dbPath}) => RustLib
    .instance
    .api
    .crateApiWalletBeginAccountDeletionLease(dbPath: dbPath);

/// Release the account-deletion lease acquired by
/// [begin_account_deletion_lease].
Future<void> finishAccountDeletionLease({required String operationToken}) =>
    RustLib.instance.api.crateApiWalletFinishAccountDeletionLease(
      operationToken: operationToken,
    );

/// Acquire the derivation gate for a full wallet reset. The returned token
/// must remain held until both the wallet DB and secure storage have finished
/// their coordinated cleanup.
Future<String> beginWalletResetLease({required String dbPath}) =>
    RustLib.instance.api.crateApiWalletBeginWalletResetLease(dbPath: dbPath);

/// Release the full-reset lease acquired by [begin_wallet_reset_lease].
Future<void> finishWalletResetLease({required String operationToken}) => RustLib
    .instance
    .api
    .crateApiWalletFinishWalletResetLease(operationToken: operationToken);

/// Fail closed for destructive account operations while a live process owns a
/// derivation lease. A stale sidecar without a held OS lock is not considered
/// live after a crash.
Future<bool> isSoftwareAccountDerivationLocked({required String dbPath}) =>
    RustLib.instance.api.crateApiWalletIsSoftwareAccountDerivationLocked(
      dbPath: dbPath,
    );

/// Compensate a just-derived account before Dart metadata commits. The caller
/// must prove ownership of the same native derivation lease.
Future<void> deleteAccountUnderSoftwareAccountDerivationLease({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String operationToken,
}) => RustLib.instance.api
    .crateApiWalletDeleteAccountUnderSoftwareAccountDerivationLease(
      dbPath: dbPath,
      network: network,
      accountUuid: accountUuid,
      operationToken: operationToken,
    );

/// Delete an account while Dart retains the shared mutation gate across its
/// remaining secure-storage and account-state cleanup.
Future<void> deleteAccountUnderAccountDeletionLease({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String operationToken,
}) => RustLib.instance.api.crateApiWalletDeleteAccountUnderAccountDeletionLease(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  operationToken: operationToken,
);

Future<bool> isSoftwareWalletLinkAccountImported({
  required String mnemonic,
  required String bip39Passphrase,
  required String network,
  required String dbPath,
  required int zip32AccountIndex,
}) => RustLib.instance.api.crateApiWalletIsSoftwareWalletLinkAccountImported(
  mnemonic: mnemonic,
  bip39Passphrase: bip39Passphrase,
  network: network,
  dbPath: dbPath,
  zip32AccountIndex: zip32AccountIndex,
);

/// Import a hardware wallet account using a UFVK (no mnemonic/seed needed).
Future<AccountCreationResult> importHardwareAccount({
  required String dbPath,
  required String network,
  required String name,
  required String ufvkString,
  required List<int> seedFingerprint,
  required int zip32Index,
  BigInt? birthdayHeight,
}) => RustLib.instance.api.crateApiWalletImportHardwareAccount(
  dbPath: dbPath,
  network: network,
  name: name,
  ufvkString: ufvkString,
  seedFingerprint: seedFingerprint,
  zip32Index: zip32Index,
  birthdayHeight: birthdayHeight,
);

/// List all accounts in the wallet database.
Future<List<AccountInfo>> listAccounts({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiWalletListAccounts(
  dbPath: dbPath,
  network: network,
);

Future<AccountExportMetadata> getAccountExportMetadata({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiWalletGetAccountExportMetadata(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Delete an account from the wallet database.
Future<void> deleteAccount({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiWalletDeleteAccount(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Drop process-local wallet summary data after the wallet DB is deleted.
Future<void> evictWalletSummaryCache({required String dbPath}) =>
    RustLib.instance.api.crateApiWalletEvictWalletSummaryCache(dbPath: dbPath);

/// Get the Unified Address for a specific account (or first account if uuid is None).
Future<String> getUnifiedAddress({
  required String dbPath,
  required String network,
  String? accountUuid,
}) => RustLib.instance.api.crateApiWalletGetUnifiedAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Export a single account's Unified Full Viewing Key (UFVK). Works for both
/// software and hardware (Keystone) accounts.
Future<String> getAccountUfvk({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiWalletGetAccountUfvk(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Generate a new 24-word BIP-39 mnemonic phrase.
String generateMnemonic() =>
    RustLib.instance.api.crateApiWalletGenerateMnemonic();

/// Get the BIP-39 English word list used for mnemonic validation.
List<String> mnemonicWordList() =>
    RustLib.instance.api.crateApiWalletMnemonicWordList();

/// Check if a wallet database exists at the given path.
bool walletExists({required String dbPath}) =>
    RustLib.instance.api.crateApiWalletWalletExists(dbPath: dbPath);

/// Ensure an existing wallet database has the schema required by this build.
Future<void> ensureWalletDbMigrated({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiWalletEnsureWalletDbMigrated(
  dbPath: dbPath,
  network: network,
);

/// Validate a mnemonic phrase (checks word count and validity).
bool validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletValidateMnemonic(mnemonic: mnemonic);

/// Get the next transparent receive address for a specific account.
///
/// This is read-only: it returns the first tracked external transparent address
/// that has not received a transparent output.
Future<String> getTransparentReceiveAddress({
  required String dbPath,
  required String network,
  String? accountUuid,
}) => RustLib.instance.api.crateApiWalletGetTransparentReceiveAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<List<String>> getRecentTransparentReceiveAddresses({
  required String dbPath,
  required String network,
  String? accountUuid,
  required int limit,
}) => RustLib.instance.api.crateApiWalletGetRecentTransparentReceiveAddresses(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  limit: limit,
);

/// Result of adding an account to an existing wallet.
class AccountCreationResult {
  final String accountUuid;
  final String unifiedAddress;
  final String? seedFamilyId;

  const AccountCreationResult({
    required this.accountUuid,
    required this.unifiedAddress,
    this.seedFamilyId,
  });

  @override
  int get hashCode =>
      accountUuid.hashCode ^ unifiedAddress.hashCode ^ seedFamilyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountCreationResult &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          unifiedAddress == other.unifiedAddress &&
          seedFamilyId == other.seedFamilyId;
}

/// Sensitive metadata for explicit encrypted wallet export flows.
class AccountExportMetadata {
  final int? zip32AccountIndex;
  final String? hardwareUfvk;
  final Uint8List? seedFingerprint;

  const AccountExportMetadata({
    this.zip32AccountIndex,
    this.hardwareUfvk,
    this.seedFingerprint,
  });

  @override
  int get hashCode =>
      zip32AccountIndex.hashCode ^
      hardwareUfvk.hashCode ^
      seedFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountExportMetadata &&
          runtimeType == other.runtimeType &&
          zip32AccountIndex == other.zip32AccountIndex &&
          hardwareUfvk == other.hardwareUfvk &&
          seedFingerprint == other.seedFingerprint;
}

/// Account info returned by list_accounts.
class AccountInfo {
  final String uuid;
  final String name;
  final String unifiedAddress;
  final bool isSeedAnchor;
  final bool isHardware;

  /// Opaque ZIP-32 seed fingerprint used only to group related accounts.
  final String? seedFamilyId;

  const AccountInfo({
    required this.uuid,
    required this.name,
    required this.unifiedAddress,
    required this.isSeedAnchor,
    required this.isHardware,
    this.seedFamilyId,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      unifiedAddress.hashCode ^
      isSeedAnchor.hashCode ^
      isHardware.hashCode ^
      seedFamilyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          unifiedAddress == other.unifiedAddress &&
          isSeedAnchor == other.isSeedAnchor &&
          isHardware == other.isHardware &&
          seedFamilyId == other.seedFamilyId;
}

/// Chain upgrade activation state computed from a known chain tip height.
class ChainUpgradeActivationStatus {
  final String network;
  final BigInt tipHeight;
  final BigInt? nu63ActivationHeight;
  final bool ironwoodActiveAtTip;

  const ChainUpgradeActivationStatus({
    required this.network,
    required this.tipHeight,
    this.nu63ActivationHeight,
    required this.ironwoodActiveAtTip,
  });

  @override
  int get hashCode =>
      network.hashCode ^
      tipHeight.hashCode ^
      nu63ActivationHeight.hashCode ^
      ironwoodActiveAtTip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainUpgradeActivationStatus &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          tipHeight == other.tipHeight &&
          nu63ActivationHeight == other.nu63ActivationHeight &&
          ironwoodActiveAtTip == other.ironwoodActiveAtTip;
}

/// Connected lightwalletd chain state relevant to Ironwood rollout decisions.
class ChainUpgradeStatus {
  final String network;
  final String lightwalletdChainName;
  final BigInt tipHeight;
  final BigInt lightwalletdReportedHeight;
  final BigInt lightwalletdEstimatedHeight;
  final String lightwalletdConsensusBranchId;
  final String lightwalletdUpgradeName;
  final BigInt lightwalletdUpgradeHeight;
  final BigInt? nu63ActivationHeight;
  final bool ironwoodActiveAtTip;
  final bool endpointMatchesNetwork;

  const ChainUpgradeStatus({
    required this.network,
    required this.lightwalletdChainName,
    required this.tipHeight,
    required this.lightwalletdReportedHeight,
    required this.lightwalletdEstimatedHeight,
    required this.lightwalletdConsensusBranchId,
    required this.lightwalletdUpgradeName,
    required this.lightwalletdUpgradeHeight,
    this.nu63ActivationHeight,
    required this.ironwoodActiveAtTip,
    required this.endpointMatchesNetwork,
  });

  @override
  int get hashCode =>
      network.hashCode ^
      lightwalletdChainName.hashCode ^
      tipHeight.hashCode ^
      lightwalletdReportedHeight.hashCode ^
      lightwalletdEstimatedHeight.hashCode ^
      lightwalletdConsensusBranchId.hashCode ^
      lightwalletdUpgradeName.hashCode ^
      lightwalletdUpgradeHeight.hashCode ^
      nu63ActivationHeight.hashCode ^
      ironwoodActiveAtTip.hashCode ^
      endpointMatchesNetwork.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainUpgradeStatus &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          lightwalletdChainName == other.lightwalletdChainName &&
          tipHeight == other.tipHeight &&
          lightwalletdReportedHeight == other.lightwalletdReportedHeight &&
          lightwalletdEstimatedHeight == other.lightwalletdEstimatedHeight &&
          lightwalletdConsensusBranchId ==
              other.lightwalletdConsensusBranchId &&
          lightwalletdUpgradeName == other.lightwalletdUpgradeName &&
          lightwalletdUpgradeHeight == other.lightwalletdUpgradeHeight &&
          nu63ActivationHeight == other.nu63ActivationHeight &&
          ironwoodActiveAtTip == other.ironwoodActiveAtTip &&
          endpointMatchesNetwork == other.endpointMatchesNetwork;
}

/// Native durable ownership and baseline for a software-account derivation.
/// Dart stores the token in its fence but Rust's DB record remains authoritative
/// after a process crash.
class SoftwareAccountDerivationLease {
  final String operationToken;
  final String sourceAccountUuid;
  final List<String> baselineAccountUuids;
  final String? recoveryName;
  final String? recoveryProfilePictureId;
  final String? recoveryAccountGroupName;
  final bool isPending;

  const SoftwareAccountDerivationLease({
    required this.operationToken,
    required this.sourceAccountUuid,
    required this.baselineAccountUuids,
    this.recoveryName,
    this.recoveryProfilePictureId,
    this.recoveryAccountGroupName,
    required this.isPending,
  });

  @override
  int get hashCode =>
      operationToken.hashCode ^
      sourceAccountUuid.hashCode ^
      baselineAccountUuids.hashCode ^
      recoveryName.hashCode ^
      recoveryProfilePictureId.hashCode ^
      recoveryAccountGroupName.hashCode ^
      isPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoftwareAccountDerivationLease &&
          runtimeType == other.runtimeType &&
          operationToken == other.operationToken &&
          sourceAccountUuid == other.sourceAccountUuid &&
          baselineAccountUuids == other.baselineAccountUuids &&
          recoveryName == other.recoveryName &&
          recoveryProfilePictureId == other.recoveryProfilePictureId &&
          recoveryAccountGroupName == other.recoveryAccountGroupName &&
          isPending == other.isPending;
}

/// A higher ZIP32 software account that can be imported by user choice.
class SoftwareWalletDiscoveredAccount {
  final int zip32AccountIndex;
  final String firstTransparentAddress;

  const SoftwareWalletDiscoveredAccount({
    required this.zip32AccountIndex,
    required this.firstTransparentAddress,
  });

  @override
  int get hashCode =>
      zip32AccountIndex.hashCode ^ firstTransparentAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoftwareWalletDiscoveredAccount &&
          runtimeType == other.runtimeType &&
          zip32AccountIndex == other.zip32AccountIndex &&
          firstTransparentAddress == other.firstTransparentAddress;
}

/// A software account created by mnemonic import.
class SoftwareWalletImportAccount {
  final String accountUuid;
  final String unifiedAddress;
  final int zip32AccountIndex;
  final String name;
  final bool isSeedAnchor;
  final String? seedFamilyId;

  const SoftwareWalletImportAccount({
    required this.accountUuid,
    required this.unifiedAddress,
    required this.zip32AccountIndex,
    required this.name,
    required this.isSeedAnchor,
    this.seedFamilyId,
  });

  @override
  int get hashCode =>
      accountUuid.hashCode ^
      unifiedAddress.hashCode ^
      zip32AccountIndex.hashCode ^
      name.hashCode ^
      isSeedAnchor.hashCode ^
      seedFamilyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoftwareWalletImportAccount &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          unifiedAddress == other.unifiedAddress &&
          zip32AccountIndex == other.zip32AccountIndex &&
          name == other.name &&
          isSeedAnchor == other.isSeedAnchor &&
          seedFamilyId == other.seedFamilyId;
}

/// Software account discovery result for an import attempt.
class SoftwareWalletImportDiscoveryResult {
  final bool primaryAccountAlreadyExists;
  final List<SoftwareWalletDiscoveredAccount> accounts;

  const SoftwareWalletImportDiscoveryResult({
    required this.primaryAccountAlreadyExists,
    required this.accounts,
  });

  @override
  int get hashCode => primaryAccountAlreadyExists.hashCode ^ accounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoftwareWalletImportDiscoveryResult &&
          runtimeType == other.runtimeType &&
          primaryAccountAlreadyExists == other.primaryAccountAlreadyExists &&
          accounts == other.accounts;
}

/// Result of software mnemonic import with ZIP32 account discovery.
class SoftwareWalletImportWithDiscoveryResult {
  final List<SoftwareWalletImportAccount> accounts;
  final bool didImportPrimaryAccount;

  const SoftwareWalletImportWithDiscoveryResult({
    required this.accounts,
    required this.didImportPrimaryAccount,
  });

  @override
  int get hashCode => accounts.hashCode ^ didImportPrimaryAccount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoftwareWalletImportWithDiscoveryResult &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          didImportPrimaryAccount == other.didImportPrimaryAccount;
}

/// Result of wallet creation, containing the mnemonic, unified address, and account UUID.
class WalletCreationResult {
  final String mnemonic;
  final String unifiedAddress;
  final String accountUuid;
  final String? seedFamilyId;

  const WalletCreationResult({
    required this.mnemonic,
    required this.unifiedAddress,
    required this.accountUuid,
    this.seedFamilyId,
  });

  @override
  int get hashCode =>
      mnemonic.hashCode ^
      unifiedAddress.hashCode ^
      accountUuid.hashCode ^
      seedFamilyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreationResult &&
          runtimeType == other.runtimeType &&
          mnemonic == other.mnemonic &&
          unifiedAddress == other.unifiedAddress &&
          accountUuid == other.accountUuid &&
          seedFamilyId == other.seedFamilyId;
}

/// Result of wallet import, containing the unified address and account UUID.
class WalletImportResult {
  final String unifiedAddress;
  final String accountUuid;
  final String? seedFamilyId;

  const WalletImportResult({
    required this.unifiedAddress,
    required this.accountUuid,
    this.seedFamilyId,
  });

  @override
  int get hashCode =>
      unifiedAddress.hashCode ^ accountUuid.hashCode ^ seedFamilyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletImportResult &&
          runtimeType == other.runtimeType &&
          unifiedAddress == other.unifiedAddress &&
          accountUuid == other.accountUuid &&
          seedFamilyId == other.seedFamilyId;
}
